version: "3.9"

services:

  cloudflare-tunnel:
    image: cloudflare/cloudflared
    container_name: tunnel
    hostname: tunnel
    restart: unless-stopped
    command: tunnel run
    networks:
      - tunnel
    environment:
      - "TUNNEL_TOKEN=${TUNNEL_TOKEN}"

networks:
  tunnel:
    name: tunnel
